#!/bin/bash

# Activate the environment
workon schedules.kavanaughdevelopment.com

# Pull incoming changesets
sudo -u schedules hg pull
sudo -u schedules hg update --clean

# Collect static files
sudo -u schedules python manage.py collectstatic

# Restart services
sudo service memcached restart
#sudo service nginx restart
sudo touch conf/uwsgi.ini